In [1]:
import pandas as pd

from utils_iFEMG_feature import df_save_csv, df_merge_colname

In [9]:
df1 = pd.read_csv(r"E:\Code_R\healthy_subjects_US_stat\US_tricps_mean_202403.csv", header = [0], index_col = None)
df2 = pd.read_csv(r"E:\Code_R\healthy_subjects_US_stat\US_tricps_mean.csv", header = [0], index_col = 0)

In [11]:
df1

,subject,weight,bicps_br_R,bicps_br_thickness,tricps_med_R,tricps_med_thickness,tricps_lat_R,tricps_lat_thickness
0,zjz,0.0,15.271495,33.676667,20.289057,45.386667,13.497606,27.206667
1,zjz,0.5,15.589479,33.623333,17.418899,45.020000,14.512295,27.001667
2,zjz,1.0,14.249431,35.368333,15.959884,45.966667,15.246189,26.670000
3,zjz,2.0,NaN,NaN,NaN,NaN,NaN,NaN
4,lmt,0.0,12.670007,35.400000,12.930559,25.595000,12.272467,35.240000
5,lmt,0.5,12.223571,37.168333,12.172346,25.758333,11.714645,36.048333
6,lmt,1.0,11.880825,38.360000,11.146756,24.983333,10.872331,35.246667
7,lmt,2.0,NaN,NaN,NaN,NaN,NaN,NaN
8,wcx,0.0,19.205531,25.113333,19.033735,38.388333,20.766026,23.046667
9,wcx,0.5,18.672136,25.591667,18.691850,38.465000,17.722030,21.490000
10,wcx,1.0,17.709528,28.335000,16.228259,37.330000,13.777949,22.385000
11,wcx,2.0,NaN,NaN,NaN,NaN,NaN,NaN
12,lmh,0.0,14.270408,38.430000,16.344193,40.378333,12.431731,28.580000
13,lmh,0.5,13.613365,40.018333,14.782825,39.711667,11.295300,28.511667
14,lmh,1.0,13.643641,42.160000,13.697975,39.310000,11.281126,27.918333
15,lmh,2.0,NaN,NaN,NaN,NaN,NaN,NaN
16,hpy,0.0,26.505076,40.475000,27.577589,48.561667,20.484906,26.303333
17,hpy,0.5,21.329983,40.258333,27.577589,47.621667,19.239925,26.035000
18,hpy,1.0,20.484906,43.028333,21.329983,47.848333,16.228259,26.746667
19,hpy,2.0,NaN,NaN,NaN,NaN,NaN,NaN
20,zx,0.0,13.425447,31.791667,14.760699,38.503333,12.714882,23.088333
21,zx,0.5,12.441914,34.313333,12.611056,38.408333,12.066037,22.515000
22,zx,1.0,11.915328,34.425000,11.888144,40.558333,13.295068,22.543333
23,zx,2.0,NaN,NaN,NaN,NaN,NaN,NaN

In [12]:
df = pd.concat([df1, df2], axis=0, ignore_index=True)
df

,subject,weight,bicps_br_R,bicps_br_thickness,tricps_med_R,tricps_med_thickness,tricps_lat_R,tricps_lat_thickness
0,zjz,0.0,15.271495,33.676667,20.289057,45.386667,13.497606,27.206667
1,zjz,0.5,15.589479,33.623333,17.418899,45.020000,14.512295,27.001667
2,zjz,1.0,14.249431,35.368333,15.959884,45.966667,15.246189,26.670000
3,zjz,2.0,NaN,NaN,NaN,NaN,NaN,NaN
4,lmt,0.0,12.670007,35.400000,12.930559,25.595000,12.272467,35.240000
...,...,...,...,...,...,...,...,...
59,lpy,2.0,NaN,NaN,NaN,NaN,NaN,NaN
60,zpk,0.0,12.015171,32.185833,13.118727,37.408333,11.448184,24.386667
61,zpk,0.5,11.984691,32.514167,11.363990,39.085000,10.258255,23.999167
62,zpk,1.0,11.481628,33.183333,10.837319,40.587500,9.516871,24.633333
63,zpk,2.0,NaN,NaN,NaN,NaN,NaN,NaN

In [13]:
df_save_csv(df, r"E:\Code_R\healthy_subjects_US_stat\US_data_202403\US_tricps_mean_2404all.csv")

File E:\Code_R\healthy_subjects_US_stat\US_data_202403\US_tricps_mean_2404all.csv saved!